@extends('layouts.dashboard')
@section('content')
<main class="mx-auto max-w-4xl p-6"><div class="mb-6"><h1 class="text-2xl font-bold">Tambah produk</h1><p class="mt-1 text-sm text-gray-500">Isi informasi produk, harga, stok awal, dan atributnya.</p></div>
@if($errors->any())<div class="mb-5 rounded-lg bg-red-50 p-4 text-red-700">Periksa kembali data yang dimasukkan.</div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ route('produk.store') }}" class="grid gap-5 rounded-xl bg-white p-6 shadow-sm md:grid-cols-2">@csrf
<label class="text-sm font-medium">Kode produk<input required name="code" data-product-code pattern="JS[0-9]{3,10}" minlength="5" maxlength="12" title="Gunakan format JS diikuti 3–10 angka, contoh: JS001 atau JS1000" placeholder="Contoh: JS001 atau JS1000" value="{{ old('code') }}" class="mt-1 block w-full rounded-lg border p-2.5"><span data-product-code-error class="mt-1 hidden text-xs text-rose-600">Format kode harus JS diikuti 3–10 angka, contohnya JS001 atau JS1000.</span>@error('code')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
<label class="text-sm font-medium">Nama produk<input required name="name" value="{{ old('name') }}" class="mt-1 block w-full rounded-lg border p-2.5"></label>
<label class="text-sm font-medium text-slate-700">Kategori<select required name="category_id" class="mt-1 block w-full rounded-xl border border-slate-300 p-2.5"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id') == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<span class="mt-1 block text-xs text-rose-600">Pilih kategori yang tersedia.</span>@enderror</label>
<label class="text-sm font-medium text-slate-700">Supplier <span class="font-normal text-slate-400">(opsional)</span><select name="supplier_id" class="mt-1 block w-full rounded-xl border border-slate-300 p-2.5"><option value="">Tanpa supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id') == $supplier->id)>{{ $supplier->name }}</option>@endforeach</select><span class="mt-1 block text-xs font-normal text-slate-400">Kosongkan jika produk tidak memiliki supplier.</span>@error('supplier_id')<span class="mt-1 block text-xs text-rose-600">Pilih supplier yang tersedia.</span>@enderror</label>
<label class="text-sm font-medium">Satuan<select required name="unit" class="mt-1 block w-full rounded-lg border p-2.5"><option value="">Pilih satuan</option>@foreach(['Pcs', 'Unit', 'Buah', 'Box', 'Pack', 'Kg', 'Gram', 'Liter', 'Meter', 'Set'] as $unit)<option value="{{ $unit }}" @selected(old('unit') === $unit)>{{ $unit }}</option>@endforeach</select></label>
<label class="text-sm font-medium">Stok awal<input type="number" inputmode="numeric" step="1" min="0" name="stock" value="{{ old('stock',0) }}" class="mt-1 block w-full rounded-lg border p-2.5"></label>
<label class="text-sm font-medium">Harga beli (Rp)<input required type="text" inputmode="numeric" data-currency-input data-currency-target="purchase_price" value="{{ old('purchase_price') !== null ? number_format((float) old('purchase_price'), 0, ',', '.') : '' }}" placeholder="Contoh: 700.000" class="mt-1 block w-full rounded-lg border p-2.5"><input type="hidden" name="purchase_price" value="{{ old('purchase_price') }}"></label>
<label class="text-sm font-medium">Harga jual (Rp)<input required type="text" inputmode="numeric" data-currency-input data-currency-target="selling_price" value="{{ old('selling_price') !== null ? number_format((float) old('selling_price'), 0, ',', '.') : '' }}" placeholder="Contoh: 700.000" class="mt-1 block w-full rounded-lg border p-2.5"><input type="hidden" name="selling_price" value="{{ old('selling_price') }}"></label>
<label class="text-sm font-medium">Stok minimum<input required type="number" inputmode="numeric" step="1" min="0" name="minimum_stock" value="{{ old('minimum_stock',5) }}" class="mt-1 block w-full rounded-lg border p-2.5"></label>
<label class="text-sm font-medium">Gambar produk<input type="file" accept="image/*" name="image" class="mt-1 block w-full rounded-lg border p-2.5"></label>
<label class="text-sm font-medium md:col-span-2">Deskripsi<textarea name="description" rows="3" class="mt-1 block w-full rounded-lg border p-2.5">{{ old('description') }}</textarea></label>
@foreach($attributes as $attribute)<label class="text-sm font-medium">{{ $attribute->name }}<input name="attribute_values[{{ $attribute->id }}]" value="{{ old('attribute_values.'.$attribute->id) }}" class="mt-1 block w-full rounded-lg border p-2.5"></label>@endforeach
<div class="flex gap-3 md:col-span-2"><button class="rounded-lg bg-blue-700 px-5 py-2.5 font-medium text-white">Simpan produk</button><a class="rounded-lg border px-5 py-2.5" href="{{ route('produk.index') }}">Batal</a></div></form></main>
@endsection
